module.exports = {
  ROLES: {
    PATIENT: 'PATIENT',
    DOCTOR: 'DOCTOR',
    ADMIN: 'ADMIN',
  },
  APPOINTMENT_STATUS: {
    CONFIRMED: 'CONFIRMED',
    IN_PROGRESS: 'IN_PROGRESS',
    COMPLETED: 'COMPLETED',
    CANCELLED: 'CANCELLED',
    RESCHEDULED: 'RESCHEDULED',
  },
  NOTIFICATION_TYPES: {
    BOOKING_CONFIRMATION: 'BOOKING_CONFIRMATION',
    APPOINTMENT_REMINDER: 'APPOINTMENT_REMINDER',
    LEAVE_CANCELLATION: 'LEAVE_CANCELLATION',
    MEDICATION_REMINDER: 'MEDICATION_REMINDER',
    RESCHEDULE_NOTICE: 'RESCHEDULE_NOTICE',
  },
  NOTIFICATION_STATUS: {
    SENT: 'SENT',
    FAILED: 'FAILED',
    RETRYING: 'RETRYING',
  },
  SLOT_HOLD_DURATION_MINUTES: 5,
};
